// 把 H5 项目的 16MB 资源压缩成微信小程序可用的体积（主包 ≤2MB）
import sharp from 'sharp';
import fs from 'fs';
import path from 'path';

const SRC = 'C:/mydev/majiang/majiangxiaoxiaole/assets';
const OUT = 'C:/mydev/majiang/mp-tools/static-out';
const B64 = path.join(OUT, 'b64');
fs.mkdirSync(OUT, { recursive: true });
fs.mkdirSync(B64, { recursive: true });
for (const d of ['avatars', 'tiles-face', 'hands', 'sfx', 'tile-poses', 'icons', 'bg']) fs.mkdirSync(path.join(OUT, d), { recursive: true });

const MP = 'C:/mydev/majiang/majiang-mp';
const H5 = 'C:/mydev/majiang/majiangxiaoxiaole';
// Shared game code is authored in the H5 tree, where it can be run and diffed
// against the DOM renderer, then copied into the mini-program verbatim.
const SHARED_JS = ['tile-motion.js', 'tile-poses.js', 'canvas-board.js', 'game-core.js'];
// Atlas grid mirrors W,H,COLS and ANGLES in majiangxiaoxiaole/tools/bake-tiles.py.
const ATLAS = { cellW: 180, cellH: 252, cols: 6, rows: 5 };

const report = [];
async function run(name, fn) {
  const t0 = Date.now();
  await fn();
  report.push(`${name} ok (${Date.now() - t0}ms)`);
}

// 1. 头像 23 张：256→128，png 调色板压缩
await run('avatars', async () => {
  const files = fs.readdirSync(path.join(SRC, 'avatars')).filter(f => f.endsWith('.png'));
  for (const f of files) {
    await sharp(path.join(SRC, 'avatars', f)).resize(128, 128)
      .png({ palette: true, compressionLevel: 9, quality: 80 })
      .toFile(path.join(OUT, 'avatars', f));
  }
});

// 2. 牌面 34 张：187x255→140x191，png 调色板
await run('tiles-face', async () => {
  const files = fs.readdirSync(path.join(SRC, 'tiles-face')).filter(f => f.endsWith('.png'));
  for (const f of files) {
    await sharp(path.join(SRC, 'tiles-face', f)).resize({ width: 140 })
      .png({ palette: true, compressionLevel: 9, quality: 85 })
      .toFile(path.join(OUT, 'tiles-face', f));
  }
});

// 3. 洗牌的手：724x2172→高度 420，保留透明通道
await run('hands', async () => {
  await sharp(path.join(SRC, 'hands', 'right-hand-long.png')).resize({ height: 420 })
    .png({ compressionLevel: 9, quality: 80 })
    .toFile(path.join(OUT, 'hands', 'right-hand-long.png'));
});

// 4. CSS 引用的大图转 base64（wxss 的 background-image 只支持 data URI / 网络图）
async function cssAsset(srcFile, outName) {
  const buf = await sharp(path.join(SRC, srcFile)).toBuffer();
  const ext = outName.endsWith('.jpg') ? 'jpeg' : 'png';
  const b64 = `data:image/${ext};base64,${buf.toString('base64')}`;
  fs.writeFileSync(path.join(B64, outName + '.txt'), b64);
  report.push(`${srcFile} -> ${outName} ${(buf.length / 1024).toFixed(0)}KB`);
}
// 桌面/背景树：941x1672 → 宽 640 jpeg
await run('table', async () => {
  const buf = await sharp(path.join(SRC, 'game-table-v1.png')).resize({ width: 640 }).jpeg({ quality: 70 }).toBuffer();
  fs.writeFileSync(path.join(B64, 'game-table.jpg.txt'), `data:image/jpeg;base64,${buf.toString('base64')}`);
  report.push(`game-table-v1.png -> jpg ${(buf.length / 1024).toFixed(0)}KB`);
});
await run('tree', async () => {
  const buf = await sharp(path.join(SRC, 'home-tree-v1.png')).resize({ width: 640 }).jpeg({ quality: 70 }).toBuffer();
  fs.writeFileSync(path.join(B64, 'home-tree.jpg.txt'), `data:image/jpeg;base64,${buf.toString('base64')}`);
  report.push(`home-tree-v1.png -> jpg ${(buf.length / 1024).toFixed(0)}KB`);
});
// 装饰 svg → png（小程序不支持 svg）
await run('svg-decor', async () => {
  const lotus = await sharp(path.join(SRC, 'lotus-lines.svg'), { density: 96 }).resize({ width: 600 }).png({ palette: true, compressionLevel: 9 }).toBuffer();
  fs.writeFileSync(path.join(B64, 'lotus-lines.png.txt'), `data:image/png;base64,${lotus.toString('base64')}`);
  const bamboo = await sharp(path.join(SRC, 'bamboo-shadow.svg'), { density: 96 }).resize({ width: 520 }).png({ palette: true, compressionLevel: 9 }).toBuffer();
  fs.writeFileSync(path.join(B64, 'bamboo-shadow.png.txt'), `data:image/png;base64,${bamboo.toString('base64')}`);
  report.push(`lotus ${(lotus.length / 1024).toFixed(0)}KB, bamboo ${(bamboo.length / 1024).toFixed(0)}KB`);
});
// 牌体雪碧图（pose 动画必须用 background-position，只能 base64）
await run('shells', async () => {
  await cssAsset('tile-poses/shells.png', 'shells.png');
  fs.copyFileSync(path.join(SRC, 'tile-poses/shells.png'), path.join(OUT, 'tile-poses/shells.png'));
});

// Pose matrices + atlas/box geometry as an ES module the canvas renderer can import.
await run('poses', async () => {
  const raw = fs.readFileSync(path.join(SRC, 'tile-poses/poses.js'), 'utf8');
  const poses = JSON.parse(raw.slice(raw.indexOf('['), raw.lastIndexOf(']') + 1));
  const angles = poses.map(p => p.angle);
  const step = angles[1] - angles[0];
  if (poses.length > ATLAS.cols * ATLAS.rows) throw new Error('atlas too small for ' + poses.length + ' poses');
  const mod = `// Generated by mp-tools/prep-assets.mjs - do not edit by hand.
// Atlas ${ATLAS.cols}x${ATLAS.rows}, cell ${ATLAS.cellW}x${ATLAS.cellH}px, ${poses.length} live poses.
export const ATLAS = ${JSON.stringify(ATLAS)};
export const ANGLE_MIN = ${angles[0]};
export const ANGLE_STEP = ${step};
// Box is w wide, w*BOX_RATIO tall. Shell sits at (-w*SHELL_INSET_X, -w*SHELL_INSET_Y), sized w*SHELL_W by w*SHELL_H.
export const BOX_RATIO = 1.4;
export const SHELL_INSET_X = 0.175;
export const SHELL_INSET_Y = 0.245;
export const SHELL_W = 1.35;
export const SHELL_H = 1.89;
// Face art insets a further 5% inside the box, soft-masked at the edges, multiplied onto the baked shell.
export const ART_INSET = 0.05;
export const ART_BLEND = 'multiply';
export const TILE_POSES = ${JSON.stringify(poses)};
// Continuous lean -> atlas frame + blend. Interpolate BOTH frame and matrix or the tilt visibly steps.
export function samplePose(lean) {
  const s = Math.max(0, Math.min(TILE_POSES.length - 1, (lean - ANGLE_MIN) / ANGLE_STEP));
  const i = Math.floor(s), next = Math.min(TILE_POSES.length - 1, i + 1);
  return { index: i, next, blend: s - i };
}
// Source rect for ctx.drawImage.
export function frameRect(index) {
  return { sx: (index % ATLAS.cols) * ATLAS.cellW, sy: Math.floor(index / ATLAS.cols) * ATLAS.cellH,
           sw: ATLAS.cellW, sh: ATLAS.cellH };
}
// Interpolated face projection; translation components must still be multiplied by tile width.
export function artMatrix(index, next, blend) {
  const a = TILE_POSES[index].matrix, b = TILE_POSES[next].matrix;
  return a.map((v, k) => v + (b[k] - v) * blend);
}
`;
  fs.writeFileSync(path.join(H5, 'tile-poses.js'), mod);
  report.push(`poses ${poses.length} frames -> majiangxiaoxiaole/tile-poses.js`);
});

// 5. 生成音效 wav（WebAudio 在小程序不可用，改用内置短音效）
await run('sfx', async () => {
  const SR = 22050;
  const tones = { t220: .3, t260: .05, t295: .05, t330: .05, t365: .05, t400: .05, t430: .07, t620: .1, t700: .05, t760: .18, t880: .14 };
  for (const [name, dur] of Object.entries(tones)) {
    const n = Math.round(SR * dur);
    const data = Buffer.alloc(44 + n * 2);
    data.write('RIFF', 0); data.writeUInt32LE(36 + n * 2, 4); data.write('WAVEfmt ', 8);
    data.writeUInt32LE(16, 16); data.writeUInt16LE(1, 20); data.writeUInt16LE(1, 22);
    data.writeUInt32LE(SR, 24); data.writeUInt32LE(SR * 2, 28); data.writeUInt16LE(2, 32); data.writeUInt16LE(16, 34);
    data.write('data', 36); data.writeUInt32LE(n * 2, 40);
    for (let i = 0; i < n; i++) {
      const t = i / SR;
      const env = Math.exp(-t / (dur * .38));
      const v = Math.round(Math.sin(2 * Math.PI * parseInt(name.slice(1)) * t) * env * 3200);
      data.writeInt16LE(v, 44 + i * 2);
    }
    fs.writeFileSync(path.join(OUT, 'sfx', name + '.wav'), data);
  }
  report.push('sfx 11 tones');
});

// 6. 体积报告
function dirSize(p) {
  let s = 0;
  for (const f of fs.readdirSync(p, { recursive: true })) {
    const fp = path.join(p, f);
    if (fs.statSync(fp).isFile()) s += fs.statSync(fp).size;
  }
  return s;
}
report.push(`TOTAL static-out: ${(dirSize(OUT) / 1024).toFixed(0)}KB (b64 前的实际资源)`);
// 7. Sync into the mini-program project so a copy can never be forgotten (shells.png was).
await run('sync', async () => {
  const dst = path.join(MP, 'src/static');
  for (const d of ['avatars', 'tiles-face', 'hands', 'sfx', 'tile-poses', 'icons', 'bg']) {
    fs.mkdirSync(path.join(dst, d), { recursive: true });
    for (const f of fs.readdirSync(path.join(OUT, d))) fs.copyFileSync(path.join(OUT, d, f), path.join(dst, d, f));
  }
  const game = path.join(MP, 'src/game');
  fs.mkdirSync(game, { recursive: true });
  for (const f of SHARED_JS) {
    const from = path.join(H5, f);
    if (!fs.existsSync(from)) continue;
    let code = fs.readFileSync(from, 'utf8');
    // tile-motion.js is a classic script in the H5 page, which has no globals to
    // attach to in a mini-program. Rewrite the UMD tail into a real export.
    if (f === 'tile-motion.js') {
      const cut = code.indexOf('  const api=');
      if (cut < 0) throw new Error('tile-motion.js tail changed; update the ESM rewrite');
      code = 'export const TileMotion = ' + code.slice(0, cut)
        + '  return {targets,step,assignLeaners,depth};\n})(globalThis);\n';
    }
    fs.writeFileSync(path.join(game, f), code);
  }
  report.push(`synced -> src/static (${(dirSize(dst) / 1024).toFixed(0)}KB) + src/game (${SHARED_JS.length} shared modules)`);
});
console.log(report.join('\n'));
